### ISSUE TITLE
Gnome Boxes not working on Endless OS 3.4.2

### ISSUE THREAD

**Issue by Jack75Guzz** [flathub/org.gnome.Boxes#1]
I have a new Acer Swift 3 preinstalled with Endless OS 3.4.2.

Gnome Boxes from the Endless App Center is not working. Any help to fix this would be appreciated. I've already posted on Endless Community; they suggest I try here. I have uninstalled and reinstalled a number of times and downloaded so-called updates as prompted, all to no avail.

[eos-diagnostic-180613_055304_UTC+0700.txt](https://github.com/flathub/org.gnome.Boxes/files/2096211/eos-diagnostic-180613_055304_UTC.0700.txt)

![screenshot from 2018-06-13 05-40-31](https://user-images.githubusercontent.com/40219515/41323792-051168de-6edb-11e8-9399-c82b26c2672a.png)

Many thanks.

**Comment by AsciiWolf** [comment]
Try installing it manually from the Terminal:
`flatpak install flathub org.gnome.Boxes`

**Comment by Jack75Guzz** [comment]
Thanks for the reply. I have tried that already; it doesn't work.

**Comment by Jack75Guzz** [comment]
Thanks for your input, Matthew.

Boxes has been working for a while, but I have been plagued by a ton of
phantom update requests on Endless App Centre for around three months.

I bought an Acer Swift 3 with Endless pre-installed, and there's no way to
remove it. Frankly, I wish I hadn't bought it.

I'm still waiting for the Endless team to get to the root of the phantom
problem, and provide a solution.

If you have any ideas, please let me know.

Cheers.

Jack

**Comment by mwleeds** [comment]
@Jack75Guzz sounds like you can close this issue then. Sorry you've had issues with issues with Endless. You could try running `flatpak update` in a Terminal. After the next release of Endless comes out (3.4.6, August 6th roughly) you can try running `sudo flatpak repair`. You can also boot from a USB drive with another OS on it and reformat the computer if you want to get rid of Endless.

**Comment by Jack75Guzz** [comment]
Many thanks.

**Comment by yomofo2s** [comment]
i cannot launch my Genome Box too.
