### ISSUE TITLE
USB Redirection Failed

### ISSUE THREAD

**Issue by steffenskov** [flathub/org.gnome.Boxes#102]
I'm running OpenSuse Tumbleweed with Gnome desktop, and I've installed a Windows 11 VM in Gnome Boxes. The VM has spice guest additions installed as well.
Gnome Boxes has been installed directly from the OpenSuse repository - no Flatpak, Snap or AppImage.

When trying to redirect a USB drive to the VM (or in fact any USB device), the toggle immediately goes back to off and a message appears at the bottom of the screen saying "USB Redirection Failed"

I've used the feature in the past (albeit on a Fedora host), and I'm a bit at a loss as to how to investigate the cause.
Oh and I did in fact go as far as reinstalling the entire host system - same outcome :-/

**Comment by felipeborges** [comment]
This is the bugtracker for the Boxes Flatpak. Refer to gitlab.gnome.org/gnome/gnome-boxes for general issues like yours.

Could you please run gnome-boxes from the commandline with `G_MESSAGES_DEBUG=all gnome-boxes` and share the output in the issue report? This will likely contain more information to why the redirection failed.

**Comment by steffenskov** [comment]
So sorry about that - I obviously wasn't paying sufficient attention :man_facepalming: 

Thanks for the tip regarding debug output, I'll make use of that and go to gitlab with whatever output it gives me :-)
