### ISSUE TITLE
Black theme disappeared

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Boxes#11]

**Comment by felipeborges** [comment]
- What's your host operating system?
- Which `flatpak --version` you have?
- What's the `flatpak info org.gnome.Boxes//stable` output?
- Does it work if you run it with `flatpak run --env=GTK_THEME=Adwaita:dark org.gnome.Boxes` ?

Thanks for your report!

**Comment by LeandroStanger** [comment]
-   What's your host operating system?
```
Endless OS
```
-   Which flatpak --version you have?
```
Flatpak 1.0.0
```
-   What's the flatpak info org.gnome.Boxes//stable output?
```
Ref: app/org.gnome.Boxes/x86_64/stable
ID: org.gnome.Boxes
Arq.: x86_64
Ramo: stable
Origem: flathub
ID de coleção: org.flathub.Stable
Data: 2018-10-24 16:26:00 +0000
Assunto: Remove redundant build flags (#10) (8982ab56)
Commit: 5f61d452550c3adecceedb2f46d06463a980a66e7aebfbda0752b91bbecf8915
Pai: d26931e637dc557845a434d53532b692024896cd064cf0d93159db454f2b10cc
Localização: /var/lib/flatpak/app/org.gnome.Boxes/x86_64/stable/5f61d452550c3adecceedb2f46d06463a980a66e7aebfbda0752b91bbecf8915
Tamanho instalado: 486,9 MB
Runtime: org.gnome.Platform/x86_64/3.30
Sdk: org.gnome.Sdk/x86_64/3.30
```
-   Does it work if you run it with flatpak run --env=GTK_THEME=Adwaita:dark org.gnome.Boxes ?

![captura de tela de 2018-10-26 09-01-53](https://user-images.githubusercontent.com/26097419/47565209-22af3280-d8fe-11e8-9f15-76c41bbd0898.png)

**Comment by nedrichards** [comment]
I still see it on 3.30.2 on a very similar endless system.

**Comment by felipeborges** [comment]
@LeandroStanger is this issue still valid?

**Comment by felipeborges** [comment]
Please REOPEN if still valid.

**Comment by somas95** [comment]
Happens on ArchLinux too

Flatpak 1.5.0
Gnome-boxes 3.34.1-64afa3d6
![If I try to inspect the application, no theme is set. Choosing "Adwaita" from the dropdown, the dark theme comes back](https://user-images.githubusercontent.com/8913975/66719183-c2562100-edec-11e9-84ec-4b02fc6a8a95.png)
