### ISSUE TITLE
Add Boxes Beta

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Boxes#14]

**Comment by felipeborges** [comment]
Are there other GNOME apps shipping their Betas in Flathub?

I was under the impression that we only ship stable in Flathub. It would be nice to be able to offer both though.

**Comment by nedrichards** [comment]
As of today, you get access to a beta channel and other goodies https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/

**Comment by felipeborges** [comment]
@nedrichards omg, that is awesome! Thank you!

I will get the Boxes beta in asap.

**Comment by felipeborges** [comment]
The Beta is now available! Please test it and let me know if something goes wrong. Your help is much appreciated!
