### ISSUE TITLE
Boxes cannot access the virtualization backend  - Ubuntu Cosmic

### ISSUE THREAD

**Issue by fbodr** [flathub/org.gnome.Boxes#18]
I installed boxes from flathub, and Im getting the error from the subjet. 
Im running ubuntu cosmit, and flatpak from alex larson ppa.
virt-manager works properly. Gnome-boxes installed from apt also work.
I tried killing the daemon before running as stated in another issue, but the problem persists.

Here is the console output:
flatpak run org.gnome.Boxes

(gnome-boxes:2): Gtk-WARNING **: 14:40:14.259: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:2): Gtk-WARNING **: 14:40:14.260: GtkListBox with a model will ignore sort and filter functions
Tracker-Message: 14:40:14.355: Could not get mtime for 'file:///home/fdr/.var/app/org.gnome.Boxes/cache/tracker/meta.db': Error when getting information for file “/home/fdr/.var/app/org.gnome.Boxes/cache/tracker/meta.db”: No such file or directory

(gnome-boxes:2): Tracker-WARNING **: 14:40:14.355: Falling back to bus backend, the direct backend failed to initialize: Could not open sqlite3 database:'/home/fdr/.var/app/org.gnome.Boxes/cache/tracker/meta.db': unable to open database file
Error setting up default broker: Failed to start storage pool: cannot open directory '/home/ubuntu/fdr/.var/app/org.gnome.Boxes/data/gnome-boxes/images': No such file or directory

(gnome-boxes:2): Boxes-WARNING **: 14:40:14.656: (../src/app.vala:452):boxes_app_setup_default_source_co: runtime check failed: (default_connection != null)

--- 
Info
flatpak info org.gnome.Boxes

GNOME Boxes - Simple remote and virtual machines

          ID: org.gnome.Boxes
         Ref: app/org.gnome.Boxes/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.32.0.1
     License: LGPL-2.1+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 497,5 MB
     Runtime: org.gnome.Platform/x86_64/3.30
         Sdk: org.gnome.Sdk/x86_64/3.30

      Commit: a2beee8d598f765af591ed8c47ffbfc48a7cd226e198d9d15b5cbe6c66fb7a56
      Parent: ccb29b388ddbb45b971fa8642ad1b527cd3da3675b5e5d783ba7a6c8e21a030a
     Subject: Update spice-gtk  and carry "cursor disappear" patches (1a1a30ec)
        Date: 2019-03-18 12:35:36 +0000

--
flatpak version

apt-cache policy flatpak
flatpak:
  Installed: 1.3.1-flatpak1~cosmic
  Candidate: 1.3.1-flatpak1~cosmic
  Version table:
 *** 1.3.1-flatpak1~cosmic 500
        500 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.7-0ubuntu0.18.10.1 500
        500 http://br.archive.ubuntu.com/ubuntu cosmic-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu cosmic-security/universe amd64 Packages
     1.0.4-1 500
        500 http://br.archive.ubuntu.com/ubuntu cosmic/universe amd64 Packages

**Comment by felipeborges** [comment]
Did you move your /home folder recently?

It seems that libvirt fails to start a storage pool in  '/home/ubuntu/fdr/.var/app/org.gnome.Boxes/data/gnome-boxes/image but all the other debug messages seem to imply that your /home prefix is /home/fdr/ etc....

**Comment by fbodr** [comment]
No, this is a clean install, but, I'm running Fedora Silverblue 30, which has /home/fdr as a symlink into /var/home/fdr

Enviado via ProtonMail móvel

-------- Mensagem Original --------
Ativo 13 de mai de 2019 09:02, Felipe Borges escreveu:

**Comment by fbodr** [comment]
It is possible. I did re install that machine and can't test it anymore . I guess it's better to close this. :)
