### ISSUE TITLE
Bizarre screen after update 3.32.0.1-5fa4fe0d

### ISSUE THREAD

**Issue by felipehw** [flathub/org.gnome.Boxes#22]
I got the newest Gnome Boxes and the problem remains.
I'm stuck with a bizarre screen and I don't see an option to disable the 3D acceleration (i saw something like that in a print screen from Gnome Boxes Twitter account).
How can I force Gnome Boxes to show the option to disable the 3D acceleration?
Thanks!

```
GNOME Boxes - Simple remote and virtual machines

          ID: org.gnome.Boxes
         Ref: app/org.gnome.Boxes/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.32.0.1
     License: LGPL-2.1+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 497,5 MB
     Runtime: org.gnome.Platform/x86_64/3.30
         Sdk: org.gnome.Sdk/x86_64/3.30

      Commit: a2beee8d598f765af591ed8c47ffbfc48a7cd226e198d9d15b5cbe6c66fb7a56
      Parent: ccb29b388ddbb45b971fa8642ad1b527cd3da3675b5e5d783ba7a6c8e21a030a
     Subject: Update spice-gtk  and carry "cursor disappear" patches (1a1a30ec)
        Date: 2019-03-18 12:35:36 +0000
```

**Comment by felipeborges** [comment]
Can you share the output of `flatpak --gl-drivers` ?

**Comment by felipeborges** [comment]
Could you open the Properties of the given VM and go to System -> Troubleshooting Logs, and paste the content here?

Thanks

**Comment by felipehw** [comment]
```
$ flatpak --gl-drivers
default
host
```

**Comment by felipehw** [comment]
Troubleshooting Logs in a attached file.
[Boxes log.txt](https://github.com/flathub/org.gnome.Boxes/files/3040173/Boxes.log.txt)

**Comment by milloni** [comment]
same here, will try to gather info later

**Comment by milloni** [comment]
btw this is not relatedto nvidia as I'm on i965

**Comment by felipehw** [comment]
The problem for me is resolved!
I don't when but I tried again today ... after a update (I don't if there is something relationed) and works!
I'll close this. If someone needs, can be reopen.
