### ISSUE TITLE
BSoD when attempting Windows 10 installation

### ISSUE THREAD

**Issue by kurobeats** [flathub/org.gnome.Boxes#26]
Occurs every time when attempting to install Windows 10. No part of the install progresses.

![Screenshot from 2019-04-13 13-13-24](https://user-images.githubusercontent.com/4091936/56075030-68997d80-5dee-11e9-97fa-ec95b1695400.png)

**Comment by felipeborges** [comment]
Could you please run Boxes from the command line and paste here what's the output?

`G_MESSAGES_DEBUG=all flatpak run org.gnome.Boxes`

**Comment by kurobeats** [comment]
It's a big one, so I'll attach.
[gb-db.txt](https://github.com/flathub/org.gnome.Boxes/files/3141915/gb-db.txt)

**Comment by man0lis** [comment]
I could fix this issue on my system by running:
`# echo 1 > /sys/modules/kvm/parameters/ignore_msrs`
or by adding
`options kvm ignore_msrs=1`
to /etc/modprobe.d/kvm.conf

**Comment by kurobeats** [comment]
thanks for the work around.

**Comment by ispanos** [comment]
Is this work-around still needed? Because I still get this blue screen. (freshly installed Fedora 34)
