### ISSUE TITLE
Auto close 

### ISSUE THREAD

**Issue by jessemoreirao** [flathub/org.gnome.Boxes#41]
(gnome-boxes:2): Gtk-WARNING **: 19:12:21.136: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:2): Gtk-WARNING **: 19:12:21.138: GtkListBox with a model will ignore sort and filter functions

(gnome-boxes:2): dconf-WARNING **: 19:12:21.213: failed to commit changes to dconf: Erro ao chamar a linha de comandos “dbus-launch --autolaunch=5758f0daf7504a9f8a2bbafb5520df49 --binary-syntax --close-stderr”: Processo filho concluiu com código 1

(gnome-boxes:2): Boxes-CRITICAL **: 19:12:21.263: media-manager.vala:226: Error connecting to Tracker: Failed to load SPARQL backend: Erro ao chamar a linha de comandos “dbus-launch --autolaunch=5758f0daf7504a9f8a2bbafb5520df49 --binary-syntax --close-stderr”: Processo filho concluiu com código 1

(gnome-boxes:2): dconf-WARNING **: 19:12:21.791: failed to commit changes to dconf: Erro ao chamar a linha de comandos “dbus-launch --autolaunch=5758f0daf7504a9f8a2bbafb5520df49 --binary-syntax --close-stderr”: Processo filho concluiu com código 1

(gnome-boxes:2): dconf-WARNING **: 19:12:21.825: failed to commit changes to dconf: Erro ao chamar a linha de comandos “dbus-launch --autolaunch=5758f0daf7504a9f8a2bbafb5520df49 --binary-syntax --close-stderr”: Processo filho concluiu com código 1

(gnome-boxes:2): dconf-WARNING **: 19:12:21.839: failed to commit changes to dconf: Erro ao chamar a linha de comandos “dbus-launch --autolaunch=5758f0daf7504a9f8a2bbafb5520df49 --binary-syntax --close-stderr”: Processo filho concluiu com código 1
Error setting up default broker: Não foi possível abrir qemu+unix:///session: falha ao conectar o soquete ao '/app/var/run/libvirt/libvirt-sock': Arquivo ou diretório inexistente

(gnome-boxes:2): Boxes-WARNING **: 19:12:21.848: (../src/app.vala:449):boxes_app_setup_default_source_co: runtime check failed: (default_connection != null)

** (gnome-boxes:2): CRITICAL **: 19:12:22.209: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.209: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.209: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.210: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.210: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.210: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.210: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.315: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.320: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.331: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.331: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.349: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.350: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.350: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.350: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.350: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.350: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.350: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.449: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.449: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.457: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.457: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.465: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.472: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.472: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.472: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.472: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.472: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.486: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.486: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.486: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.486: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.486: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.486: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.487: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.507: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.510: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.518: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.518: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.523: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.523: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.523: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.523: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.523: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.523: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.523: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.574: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.574: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.578: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.578: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.597: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.599: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.605: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.605: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.606: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.606: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.606: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.606: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.606: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.638: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.639: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.639: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.639: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.639: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.639: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.648: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.648: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.649: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.649: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.649: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.649: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.649: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.666: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.666: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.666: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.666: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.666: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.666: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.671: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.671: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.675: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.675: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.682: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.682: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.682: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.682: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.682: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.682: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.682: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.700: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.704: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.710: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.715: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.716: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.792: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.793: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.794: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.797: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.797: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.797: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.797: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.797: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.797: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.858: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.858: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.858: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.858: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.861: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.866: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.867: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.867: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.867: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.867: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.867: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.890: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.965: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.965: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.965: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.965: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.966: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.966: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.966: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.966: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.997: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.999: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.999: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:22.999: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.005: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.005: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.005: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.005: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.005: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.006: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.007: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.010: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.012: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.012: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.012: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.021: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.021: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.021: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.021: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.021: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.021: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.021: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.033: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.039: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.084: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.084: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.084: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.084: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.085: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.085: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.085: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.085: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.108: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.108: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.108: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.108: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.109: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.109: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.109: osinfo_entity_set_param: assertion 'value != NULL' failed

** (gnome-boxes:2): CRITICAL **: 19:12:23.109: osinfo_entity_set_param: assertion 'value != NULL' failed

(gnome-boxes:2): dconf-WARNING **: 19:12:24.884: failed to commit changes to dconf: Erro ao chamar a linha de comandos “dbus-launch --autolaunch=5758f0daf7504a9f8a2bbafb5520df49 --binary-syntax --close-stderr”: Processo filho concluiu com código 1

**Comment by felipeborges** [comment]
What's your distribution and `flatpak --version`?

**Comment by felipeborges** [comment]
Please REOPEN if the issue persists.
