### ISSUE TITLE
Cannot find IP to connect from host using ssh

### ISSUE THREAD

**Issue by Yajo** [flathub/org.gnome.Boxes#49]
When I used rpm gnome-boxes, I always was able to log in with ssh.

With flatpak version I cannot. Is there anything special to be done to get that? All boxes seem to have IP 10.0.2.15.

**Comment by felipeborges** [comment]
Unfortunately, we still don't support the bridge network for Flatpaks.

The bridge network works by having qemu-bridge-helper being a privileged binary (suid bit) that creates a socket pair with /dev/net/tun... 

we can't escalate privileges from within the Flatpak sandbox. To workaround that we plan on introducing a Flatpak Portal.

**Comment by felipeborges** [comment]
Stay tuned in https://gitlab.gnome.org/GNOME/gnome-boxes/-/issues/232 for further developments in this regard.
