### ISSUE TITLE
Use fallback-x11

### ISSUE THREAD

**Issue by mat8913** [flathub/org.gnome.Boxes#5]
As far as I can tell, Boxes doesn't actually need X11 and works perfectly fine under pure Wayland. If that is indeed the case, then please add `--socket=fallback-x11` to `finish-args`.

Here's a quote from https://github.com/flatpak/flatpak/blob/master/NEWS:

>  * A new `fallback-x11` permission grants X11 access, but only if the user is running in a X11 session. For applications that support both Wayland and X11, this can be used to ensure that the app doesn't have unnecessary X11 access while in Wayland, but still works in an X11 session.

**Comment by TingPing** [comment]
Note it will prevent older flatpak versions from working (< 0.10.3 I think).

**Comment by felipeborges** [comment]
@TingPing thanks for pointing that out. I see that Debian stable[[0]] ships an older version than 0.10.3. Fedora and Ubuntu (latest LTS) have newer. Debian Buster is expected to be released early 2019, so we would break it for a few months. Seems worth it to me. :smile: 

Thoughts?

[0]: https://packages.debian.org/stretch/flatpak

**Comment by TingPing** [comment]
Seems fine.
