### ISSUE TITLE
Gnome Boxes cannot change disk size

### ISSUE THREAD

**Issue by udhis** [flathub/org.gnome.Boxes#51]
![Screenshot from 2020-08-13 19-03-10](https://user-images.githubusercontent.com/69633016/90134432-5ee5a880-dd9b-11ea-90b4-05da8d5aa5da.png)

I am use Endless OS 3

**Comment by felipeborges** [comment]
Thanks for reporting this issue.

Could you please run Boxes from the command-line and comment here with the output?

1. Open a Terminal
2. Type: `flatpak run org.gnome.Boxes`
3. Once Boxes opens, try to change the disk size of your VM
4. Go back to the Terminal window and copy the Boxes output and paste it here as a comment.

**Comment by udhis** [comment]
output from Terminal

acer@endless:~$ flatpak run org.gnome.Boxes

(gnome-boxes:3): Boxes-WARNING **: 13:10:41.385: shared-folders.vala:82: File exists

(gnome-boxes:3): Boxes-WARNING **: 13:10:41.386: shared-folders.vala:82: File exists

(gnome-boxes:3): Gtk-WARNING **: 13:10:42.856: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:3): Gtk-WARNING **: 13:10:42.858: GtkListBox with a model will ignore sort and filter functions

(gnome-boxes:3): Tracker-CRITICAL **: 13:10:51.295: tracker_sparql_cursor_real_get_boolean: assertion '_tmp0_ == TRACKER_SPARQL_VALUE_TYPE_BOOLEAN' failed

(gnome-boxes:3): Boxes-WARNING **: 13:10:57.889: libvirt-machine.vala:275: Failed to connection to system libvirt: Unable to open qemu+unix:///system: Failed to connect socket to '/app/var/run/libvirt/libvirt-sock-ro': No such file or directory

(gnome-boxes:3): GLib-GIO-CRITICAL **: 13:10:59.035: g_file_new_for_uri: assertion 'uri != NULL' failed

(gnome-boxes:3): GLib-GIO-CRITICAL **: 13:10:59.035: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

(gnome-boxes:3): GLib-GIO-CRITICAL **: 13:10:59.039: g_file_new_for_uri: assertion 'uri != NULL' failed

(gnome-boxes:3): GLib-GIO-CRITICAL **: 13:10:59.039: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

**Comment by zakaria-chahboun** [comment]
@udhis 
First of all shutdown your vm os, Then increase the size in gnome boxes, After that you need to extend your disk inside your vm os
This is an example  with win10 vm:
![Screenshot from 2021-08-17 10-57-58](https://user-images.githubusercontent.com/18173275/129707801-16547f59-e73e-4c2b-909a-0300a7784e3e.png)

**Comment by felipeborges** [comment]
I have recently answered a similar question at https://gitlab.gnome.org/GNOME/gnome-boxes/-/issues/714#note_1234385

**Comment by algaly** [comment]
This worked for me.
Extending the disk on disk was not working even when i changed the size (it returned to the original size).
Cloning my virtual machine and adding extra space to to the new one worked!
