### ISSUE TITLE
¿Como puedo compartir archivos entre mi Host y la maquina virtual con Cajas?

### ISSUE THREAD

**Issue by Cristiancastano710** [flathub/org.gnome.Boxes#52]
@felipeborges #52 
Cree una maquina virtual con W10 y quiero compartir archivos entre mi host y la maquina pero no me deja, arrastro el archivo desde mi ventana de documentos (Host) hasta la maquina virtual (W10), me aparece el signo para copiar en la maquina virtual pero no pasa nada. ¿esto es posible o no lo tiene cajas? sino es posible, ¿la maquina virtual puede leer memorias USB? porque lo intente y tampoco funciona.

Mil gracias por la ayuda

![Captura de pantalla de 2020-09-05 17-26-32](https://user-images.githubusercontent.com/70823151/92314443-1174e980-ef9d-11ea-87e6-80f12579c210.png)

**Comment by felipeborges** [comment]
You need to install the spice guest tools in the Windows machine. https://www.spice-space.org/download/windows/spice-guest-tools/spice-guest-tools-latest.exe
