### ISSUE TITLE
Application name metadata incorrect (small typo)

### ISSUE THREAD

**Issue by ultraviolet-1986** [flathub/org.gnome.Boxes#56]
Hi,

Small issue, I noticed while sorting through my flatpaks that GNOME Boxes shows up in my terminal as `GNOME Boxesi`, see below:

```bash
Name                                      Application ID                        Version  Branch  Origin   Installation
GNOME Boxesi                              org.gnome.Boxes                       3.38.1   stable  flathub  system
```

Thanks, this flatpak helped me move to Silverblue full-time!

**Comment by felipeborges** [comment]
Thanks for your bug report.

I discovered that this is an issue with our EN_GB translation. It doesn't affect other locales. See https://gitlab.gnome.org/GNOME/gnome-boxes/-/blob/master/po/en_GB.po#L25

I reported the issue to our British English translation team. Once the update the translation in the `gnome-3-38`, I will roll a Flathub update to fix this for our users.

**Comment by SuborbitalPigeon** [comment]
Should be fixed now. Apologies for the issue.

**Comment by felipeborges** [comment]
Thank you very much! I will roll an update.

**Comment by felipeborges** [comment]
https://flathub.org/builds/#/builders/32/builds/30987

**Comment by ultraviolet-1986** [comment]
Can confirm it's all correct after the update. Thanks again! Marking as closed now ^_^b
