### ISSUE TITLE
Gnome Boxes cannot connect to libvirtd

### ISSUE THREAD

**Issue by lentzi90** [flathub/org.gnome.Boxes#6]
I have installed Gnome Boxes from flathub, but it does not work. I’m getting the following message when starting it: “Boxes cannot access the virtualization backend”. In the terminal I can see the following:

```
$ flatpak run org.gnome.Boxes 

(gnome-boxes:2): Gtk-WARNING **: 21:14:51.473: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:2): Gtk-WARNING **: 21:14:51.474: GtkListBox with a model will ignore sort and filter functions
Tracker-Message: 21:14:51.563: Could not get mtime for 'file:///home/lennart/.var/app/org.gnome.Boxes/cache/tracker/meta.db': Error when getting information for file “/home/lennart/.var/app/org.gnome.Boxes/cache/tracker/meta.db”: No such file or directory

(gnome-boxes:2): Tracker-WARNING **: 21:14:51.563: Falling back to bus backend, the direct backend failed to initialize: Could not open sqlite3 database:'/home/lennart/.var/app/org.gnome.Boxes/cache/tracker/meta.db': unable to open database file
Error setting up default broker: Unable to open qemu+unix:///session: Failed to connect socket to '/run/user/1000/libvirt/libvirt-sock': No such file or directory

(gnome-boxes:2): Boxes-WARNING **: 21:14:56.917: (/run/build/gnome-boxes/src/app.vala:446):boxes_app_setup_default_source_co: runtime check failed: (default_connection != null)
```

The above is from a laptop running Fedora Silverblue 29 beta. I have another PC running Fedora 28 that has a similar problem:

```
$ flatpak run org.gnome.Boxes 

(gnome-boxes:2): Gtk-WARNING **: 18:36:26.500: Locale not supported by C library.
	Using the fallback 'C' locale.

(gnome-boxes:2): Gtk-WARNING **: 18:36:26.600: GtkFlowBox with a model will ignore sort and filter functions

(gnome-boxes:2): Gtk-WARNING **: 18:36:26.601: GtkListBox with a model will ignore sort and filter functions
Tracker-Message: 18:36:26.784: Could not get mtime for 'file:///home/lennart/.var/app/org.gnome.Boxes/cache/tracker/meta.db': Error when getting information for file ?/home/lennart/.var/app/org.gnome.Boxes/cache/tracker/meta.db?: No such file or directory

(gnome-boxes:2): Tracker-WARNING **: 18:36:26.786: Falling back to bus backend, the direct backend failed to initialize: Could not open sqlite3 database:'/home/lennart/.var/app/org.gnome.Boxes/cache/tracker/meta.db': unable to open database file

(process:30): Gtk-WARNING **: 18:36:26.818: Locale not supported by C library.
	Using the fallback 'C' locale.
Error setting up default broker: Unable to open qemu+unix:///session: Cannot recv data: Connection reset by peer

(gnome-boxes:2): Boxes-WARNING **: 18:36:27.105: (../src/app.vala:451):boxes_app_setup_default_source_co: runtime check failed: (default_connection != null)

(gnome-boxes:2): Boxes-WARNING **: 18:36:27.300: unattended-installer.vala:80: Failed to connect to D-Bus service 'org.freedesktop.Accounts': Could not connect: No such file or directory

(gnome-boxes:2): Boxes-WARNING **: 18:36:27.300: util-app.vala:493: Failed to find system timezone: Timezone file in unexpected location '/run/host/monitor/localtime'
```

This second system has a working libvirt installation that I use with Vagrant.

Are there any additional steps that I need to follow to get it running?

**Comment by felipeborges** [comment]
Could you please run `$ flatpak info org.gnome.Boxes` and paste the result here so we could trace down the issue to the specific version?

Btw, Boxes 3.30 has just been released in Flathub. If you don't have it yet, I encourage you to update and see whether the issue persists.

Thanks for your report! I appreciate it.

**Comment by lentzi90** [comment]
Thanks for the quick response!
I updated just before reporting this just to make sure I had the latest. Here is the output:
```
$ flatpak info org.gnome.Boxes
Ref: app/org.gnome.Boxes/x86_64/stable
ID: org.gnome.Boxes
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-10-03 15:03:23 +0000
Subject: mtools: Provide newer config.guess and config.sub (800112be)
Commit: d26931e637dc557845a434d53532b692024896cd064cf0d93159db454f2b10cc
Parent: 56fe0f498817c7d9760e7ac0124b0e34fc8b9d9c0507651d6f28fa41e05c7dea
Location: /var/lib/flatpak/app/org.gnome.Boxes/x86_64/stable/d26931e637dc557845a434d53532b692024896cd064cf0d93159db454f2b10cc
Installed size: 486,9 MB
Runtime: org.gnome.Platform/x86_64/3.30
Sdk: org.gnome.Sdk/x86_64/3.30
```

**Comment by gfavaro** [comment]
I'm getting this error to:

~/ $ flatpak info org.gnome.Boxes 
Ref: app/org.gnome.Boxes/x86_64/stable
ID: org.gnome.Boxes
Arq.: x86_64
Ramo: stable
Origem: flathub
ID de coleção: org.flathub.Stable
Data: 2018-10-24 16:26:00 +0000
Assunto: Remove redundant build flags (#10) (8982ab56)
Commit: 5f61d452550c3adecceedb2f46d06463a980a66e7aebfbda0752b91bbecf8915
Pai: d26931e637dc557845a434d53532b692024896cd064cf0d93159db454f2b10cc
Localização: /var/lib/flatpak/app/org.gnome.Boxes/x86_64/stable/5f61d452550c3adecceedb2f46d06463a980a66e7aebfbda0752b91bbecf8915
Tamanho instalado: 486,9 MB
Runtime: org.gnome.Platform/x86_64/3.30
Sdk: org.gnome.Sdk/x86_64/3.30

**Comment by felipeborges** [comment]
Could you share what's your operating system and which flatpak version you have installed?

flatpak --version

**Comment by gfavaro** [comment]
Sorry about the lack of details.

I'm running latest Silverblue:


$ rpm-ostree status
State: idle
AutomaticUpdates: disabled
Deployments:
ostree://fedora-workstation:fedora/29/x86_64/silverblue
                   Version: 29.20181030.0 (2018-10-30 15:47:57)

$ flatpak --version
Flatpak 1.0.4

---
Gabriel Fávaro

**Comment by kirbyfan64** [comment]
For anyone with this issue, try `pkill virt`, `pkill qemu`, and `pkill boxes`, then re-open Boxes. I've noticed this can happen when virtd is already running in the background.

**Comment by spktkpkt** [comment]
I hope it is okay to reopen this issue, because i have the same problem it the issue doesn't seem to be OS-specific.

The Boxes GUI displays the following message at first run:
*Oops, something went wrong
Boxes cannot access the virtualization backend.*

If i try to create a new virtual machine:
*Virtualization extensions are unavailable on your system.
Check your BIOS settings to enable them.*

OS:

	$ swupd info 
	Distribution:      Clear Linux OS
	Installed version: 32760

Flatpack info Boxes:

	$ flatpak info org.gnome.Boxes

	GNOME Boxes - Simple remote and virtual machines

		      ID: org.gnome.Boxes
		     Ref: app/org.gnome.Boxes/x86_64/stable
		    Arch: x86_64
		  Branch: stable
		 Version: 3.36.2
		 License: LGPL-2.1+
		  Origin: flathub
	  Collection: org.flathub.Stable
	Installation: system
	   Installed: 679.7 MB
		 Runtime: org.gnome.Platform/x86_64/3.36
		     Sdk: org.gnome.Sdk/x86_64/3.36

		  Commit: 2bfc01aeeed3fd939ce376d133d96ccaa36752bd3ddad6f510d666c77ff1b648
		  Parent: 814fd24ebfc4efaaedd3df946fa2966bf005c7df726af91ed1d369e7d9b19918
		 Subject: Release 3.36.0 (cc0a7643)
		    Date: 2020-03-30 16:37:52 +0000

Flatpak version:

	$ flatpak --version
	Flatpak 1.6.2

First run:

	$ flatpak run org.gnome.Boxes
	Gtk-Message: 18:56:08.794: Failed to load module "pk-gtk-module"
	Gtk-Message: 18:56:08.795: Failed to load module "pk-gtk-module"

	(gnome-boxes:2): Gtk-WARNING **: 18:56:08.829: GtkFlowBox with a model will ignore sort and filter functions

	(gnome-boxes:2): Gtk-WARNING **: 18:56:08.830: GtkListBox with a model will ignore sort and filter functions

	(gnome-boxes:2): Tracker-WARNING **: 18:56:08.886: Falling back to bus backend, the direct backend failed to initialize: Could not find database file:'/home/me/.var/app/org.gnome.Boxes/cache/tracker/meta.db'.

	(gnome-boxes:2): Tracker-CRITICAL **: 18:56:09.264: tracker_sparql_cursor_real_get_boolean: assertion '_tmp0_ == TRACKER_SPARQL_VALUE_TYPE_BOOLEAN' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 18:56:09.283: g_file_new_for_uri: assertion 'uri != NULL' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 18:56:09.283: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 18:56:09.286: g_file_new_for_uri: assertion 'uri != NULL' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 18:56:09.286: g_file_get_basename: assertion 'G_IS_FILE (file)' failed
	Error setting up default broker: Unable to open qemu+unix:///session: Failed to connect socket to '/run/user/1000/libvirt/libvirt-sock': No such file or directory

	(gnome-boxes:2): Boxes-WARNING **: 18:56:14.426: (../src/app.vala:459):boxes_app_setup_default_source_co: runtime check failed: (default_connection != null)

	(gnome-boxes:2): Tracker-CRITICAL **: 19:02:49.317: tracker_sparql_cursor_real_get_boolean: assertion '_tmp0_ == TRACKER_SPARQL_VALUE_TYPE_BOOLEAN' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:02:49.318: g_file_new_for_uri: assertion 'uri != NULL' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:02:49.318: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:02:49.325: g_file_new_for_uri: assertion 'uri != NULL' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:02:49.325: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

Second run:

	$ flatpak run org.gnome.Boxes
	Gtk-Message: 19:07:09.714: Failed to load module "pk-gtk-module"
	Gtk-Message: 19:07:09.715: Failed to load module "pk-gtk-module"

	(gnome-boxes:2): Gtk-WARNING **: 19:07:09.749: GtkFlowBox with a model will ignore sort and filter functions

	(gnome-boxes:2): Gtk-WARNING **: 19:07:09.750: GtkListBox with a model will ignore sort and filter functions

	(gnome-boxes:2): Tracker-WARNING **: 19:07:09.854: Falling back to bus backend, the direct backend failed to initialize: Could not find database file:'/home/me/.var/app/org.gnome.Boxes/cache/tracker/meta.db'.

	(gnome-boxes:2): Tracker-CRITICAL **: 19:07:10.233: tracker_sparql_cursor_real_get_boolean: assertion '_tmp0_ == TRACKER_SPARQL_VALUE_TYPE_BOOLEAN' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:07:10.252: g_file_new_for_uri: assertion 'uri != NULL' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:07:10.252: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:07:10.255: g_file_new_for_uri: assertion 'uri != NULL' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:07:10.255: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

	(gnome-boxes:2): Tracker-CRITICAL **: 19:07:28.087: tracker_sparql_cursor_real_get_boolean: assertion '_tmp0_ == TRACKER_SPARQL_VALUE_TYPE_BOOLEAN' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:07:28.088: g_file_new_for_uri: assertion 'uri != NULL' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:07:28.088: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:07:28.095: g_file_new_for_uri: assertion 'uri != NULL' failed

	(gnome-boxes:2): GLib-GIO-CRITICAL **: 19:07:28.095: g_file_get_basename: assertion 'G_IS_FILE (file)' failed

	(gnome-boxes:2): Boxes-WARNING **: 19:07:34.301: libvirt-machine.vala:275: Failed to connection to system libvirt: Unable to open qemu+unix:///system: Failed to connect socket to '/app/var/run/libvirt/libvirt-sock-ro': No such file or directory

	(gnome-boxes:2): Boxes-WARNING **: 19:07:39.848: machine.vala:638: Failed to start kali-linux-2020: Unable to start domain: unsupported configuration: CPU mode 'host-passthrough' for x86_64 qemu domain on x86_64 host is not supported by hypervisor
