### ISSUE TITLE
Cannot add remote connection

### ISSUE THREAD

**Issue by jvnknvlgl** [flathub/org.gnome.Boxes#66]
I am unable to create a remote connection on Boxes. When I press the +-button, "Create a Virtual Machine" is opened immediately. The shortcut Shift-Ctrl-N does not work to open the remote connection menu. Is this a known issue?

**Comment by felipeborges** [comment]
Remote connections have been dropped recently from Boxes in favor of GNOME Connections. See https://feborg.es/announcing-gnome-connections/

It's already available on Flathub, in early stages of development. https://flathub.org/apps/details/org.gnome.Connections

**Comment by jvnknvlgl** [comment]
That makes sense, yes, but didn't GNOME Boxes offer spice:// and qemu://? That's not something that is in GNOME Connections right now.
