### ISSUE TITLE
[Silverblue 35] 3D Acceleration option suddenly gone. VM which had it set before crash on startup

### ISSUE THREAD

**Issue by Mershl** [flathub/org.gnome.Boxes#68]
## Description
Updated an SB35 machine today (7 days worth of updates). Noticed that many previously working VMs in Gnome Boxes (from flathub) were crashing on startup. All affected VMs had `3D acceleration` enabled. The option is no longer shown in the `Properties` pane for any VM.

Gnome Boxes logs:
```
(gnome-boxes:2): Boxes-WARNING **: 01:58:55.300: libvirt-machine.vala:290: Failed to connection to system libvirt: Unable to open qemu+unix:///system: Failed to connect socket to '/app/var/run/libvirt/virtqemud-sock-ro': No such file or directory

(gnome-boxes:2): Boxes-WARNING **: 01:59:04.219: machine.vala:644: Failed to start Fedora-Kinoite: Unable to start domain: internal error: qemu unexpectedly closed the monitor: 2021-11-08T00:59:03.993232Z qemu-system-x86_64: warning: This family of AMD CPU doesn't support hyperthreading(2)
Please configure -smp options properly or try enabling topoext feature.
2021-11-08T00:59:04.007816Z qemu-system-x86_64: -device virtio-vga-gl,id=video0,max_outputs=1,bus=pcie.0,addr=0x1: opengl is not available
```

Affected VMs (that had 3D acceleration enabled before) log:
[sb35_gnome_boxes_3d_accel_crash.txt](https://github.com/flathub/org.gnome.Boxes/files/7493563/sb35_gnome_boxes_3d_accel_crash.txt)

## Workaround
Setting the accel3d parameter manually to "no" allows VMs to boot again.

```
      <model type="virtio" heads="1" primary="yes">
        <acceleration accel3d="yes"/>   // -> setting this to "no"
      </model>
```

## System info
```
fedora:fedora/35/x86_64/silverblue
                   Version: 35.20211107.0 (2021-11-07T01:03:34Z)
```
Using latest GNOME Boxes from flathub (last updated: 2021-11-05 10:28:37 +0000)
```
GNOME Boxes	org.gnome.Boxes	41.1	stable	system
```

**Comment by Mershl** [comment]
Seems like Silverblue 35 has removed/lost `mesa-libGLU-9.0.1-5.fc35.x86_64` in the base image.

Silverblue 35 (latest):
```
$ rpm -qa "mesa*"
mesa-filesystem-21.2.5-1.fc35.x86_64
mesa-libgbm-21.2.5-1.fc35.x86_64
mesa-libglapi-21.2.5-1.fc35.x86_64
mesa-libEGL-21.2.5-1.fc35.x86_64
mesa-libxatracker-21.2.5-1.fc35.x86_64
mesa-vulkan-drivers-21.2.5-1.fc35.x86_64
mesa-dri-drivers-21.2.5-1.fc35.x86_64
mesa-libGL-21.2.5-1.fc35.x86_64
```

Kinoite 35 (latest):
```
$ rpm -qa "mesa*"
mesa-filesystem-21.2.5-1.fc35.x86_64
mesa-libgbm-21.2.5-1.fc35.x86_64
mesa-libglapi-21.2.5-1.fc35.x86_64
mesa-libEGL-21.2.5-1.fc35.x86_64
mesa-libxatracker-21.2.5-1.fc35.x86_64
mesa-vulkan-drivers-21.2.5-1.fc35.x86_64
mesa-dri-drivers-21.2.5-1.fc35.x86_64
mesa-libGL-21.2.5-1.fc35.x86_64
mesa-libGLU-9.0.1-5.fc35.x86_64
```

**Comment by loganmc10** [comment]
+1 on this, I don't see any 3d acceleration option using the GNOME Boxes flatpak on Silverblue 35

**Comment by 1player** [comment]
I can see the 3d acceleration option as of 7 Apr 2022, though I'm not sure it's actually doing anything. This issue can probably be closed.

**Comment by Mershl** [comment]
Can confirm. The issue is no longer reproduciable after upgrading to Fedora 36 and Gnome Boxes 42.0 (from flathub).
