### ISSUE TITLE
3D acceleration doesn't work on first boot of VM after the host rebooted.

### ISSUE THREAD

**Issue by TheHooly** [flathub/org.gnome.Boxes#70]
System: Galago Pro (galp5)
CPU: i7-1165G7
GPU: 1650Ti Mobile (disabled)
Host OS: Fedora Silverblue 35
Guest OS: Fedora Workstation 35

Problem:
Guest OS is not able to use 3D acceleration on first boot.

Expected behaviour:
3D acceleration working OOTB.

Steps to reproduce:
1. Reboot host OS
2. Start Gnome Boxes
3. Launch guest with 3D acceleration enabled
4. VM fails to start with `qemu-system-x86_64: -device virtio-vga-gl,id=video0,max_outputs=1,bus=pcie.0,addr=0x1: opengl is not available`
5. Launch guest with 3D acceleration disabled
6. Shutdown guest gracefully
7. Enable 3D acceleration
8. Launch guest again, now 3D acceleration works

Possibly related issue: https://github.com/flathub/org.gnome.Boxes/issues/68

**Comment by Mershl** [comment]
Do you still see this issue? I can no longer reproduce it on Fedora SB 36 and latest Gnome Boxes (from flathub).

**Comment by TheHooly** [comment]
Yes, I can still reproduce on both SB 35 and 36.

**Comment by TheHooly** [comment]
Nope, can no longer reproduce on SB 36.

**Comment by kichirouhoshino** [comment]
Hi! I'm in Fedora Silverblue 36 right now and I don't have the option for 3D Acceleration. Tried Android x86, Fedora Workstation, and Linux Mint and all of them have bad video performance. I've had this issue since Fedora 35.
