### ISSUE TITLE
Windows 10 guest unable to connect to the Internet on Debian 12 host

### ISSUE THREAD

**Issue by KairanD** [flathub/org.gnome.Boxes#89]
Hello.

In the past, I used GNOME Boxes Flatpak on Debian 12 GNOME and I was able to install and use a Windows 10 guest without issues. I ended up deciding to try Arch Linux KDE for a while and, after installing a new Windows 10 guest, everything also worked fine.

I reinstalled Debian 12 GNOME today (after some weeks using Arch) and now the Windows 10 guest does not detect that there is a network cable connected (during the install and after). I tested the Windows 10 .iso in the English (United States), English (International) and Brazilian Portuguese versions, on two different computers, and got the same result. This also happens with Windows 11 .isos.

It is worth mentioning that I tested guest Linux distros, such as Xubuntu and Linux Mint, and they managed to connect normally.

Any clues? Thanks in advance.

**Comment by felipeborges** [comment]
Let's continue the debugging in https://gitlab.gnome.org/GNOME/gnome-boxes/-/issues/1032

Thanks!
