### ISSUE TITLE
(Wayland) Desktop file name missmatch with app-id

### ISSUE THREAD

**Issue by frandmb** [flathub/org.gnome.Boxes#95]
Same as https://github.com/flathub/com.visualstudio.code/issues/429
~app-id~ wmclass is `gnome`-boxes while the desktop file named `org.gnome.Boxes.desktop`.

They should match according to Wayland spec. Affects KDE. Should be working fine on Gnome due to the usage of `StartupWMClass`.

**Comment by A6GibKm** [comment]
Thanks for the report, I had a suspicious something like this was happening. Unfortunately, this is the repository for the Flatpak distribution of the app. Please open an issue upstream https://gitlab.gnome.org/GNOME/gnome-boxes. In any case I will try to debug this when I find some time.

**Comment by A6GibKm** [comment]
I am closing, please open an issue upstream or join the discussion at the linked MRs if needed :)
